package my.service.quiz.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.Table;

@Entity
@Table(name="autogenerated_questions", schema = "quiz")
public class AutogeneratedQuestion extends Question{
}
