package my.service.quiz.entities;

import jakarta.persistence.*;
import org.json.JSONArray;
import org.json.JSONObject;
import org.springframework.boot.autoconfigure.domain.EntityScan;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;

@Table(name="autogenerated_questions", schema = "quiz")
@Entity
public class AutogeneratedQuestion extends Question {

    public AutogeneratedQuestion(int type, String task, String answer1, String answer2, String answer3, String answer4, String image){
        super(type, task, answer1, answer2, answer3, answer4, image);
    }

    public AutogeneratedQuestion(){
        super();
    }
}
