package my.service.quiz.entities;

import jakarta.persistence.*;
import org.json.JSONArray;
import org.json.JSONObject;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;

@Table(name="questions", schema = "quiz")
@Entity
public class OrdinaryQuestion extends Question {

    @Column
    public int complexity;

    @Column(name = "last_correct_answer")
    @Temporal(TemporalType.TIMESTAMP)
    public LocalDateTime lastCorrectAnswer;

    @Column(name = "class_number_if_autogenerated")
    public Integer classNumber;

    @Column
    private String topic;

    public OrdinaryQuestion(int type, String task, String answer1, String answer2, String answer3, String answer4, String topic, String image, Integer number){
        super(type, task, answer1, answer2, answer3, answer4, image);
        this.topic = topic;
    }

    public OrdinaryQuestion(){
        super();
    }

    @Override
    public JSONObject toJson() {
        JSONObject temp = super.toJson();
        if (topic != null) temp.put("topic", topic);
        return temp;
    }
}
