package my.service.quiz.entities;

import jakarta.persistence.*;
import my.service.quiz.enums.QuestionType;
import org.json.JSONArray;
import org.json.JSONObject;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;

@Table(name="questions", schema = "quiz")
@Entity
public class OrdinaryQuestion extends Question {

    @Column
    public int complexity;

    @Column(name = "last_correct_answer")
    @Temporal(TemporalType.TIMESTAMP)
    public LocalDateTime lastCorrectAnswer;

    @Column(name = "class_number_if_autogenerated")
    public Integer classNumber;

    public OrdinaryQuestion(QuestionType type, String task, String answer1, String answer2, String answer3, String answer4, String topic, String image, Integer number){
        super(type, task, answer1, answer2, answer3, answer4, topic, image);
        classNumber = number;
    }

    public OrdinaryQuestion(){
        super();
    }
}
