package my.service.quiz.entities;

import jakarta.annotation.Nullable;
import jakarta.persistence.*;

@Entity
@Table(name="quizzes_to_questions", schema = "quiz")
public
class QuizToQuestions implements Comparable<QuizToQuestions>{

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "relation_id")
    private int id;

    @ManyToOne
    @MapsId("quizId")
    @JoinColumn(name = "quiz_id")
    Quiz quiz;

    @ManyToOne
    @MapsId("id")
    @JoinColumn(name = "question_id")
    public OrdinaryQuestion question;

    @Nullable
    @ManyToOne
    @MapsId("autogeneratedQuestionId")
    @JoinColumn(name = "autogenerated_question_id")
    public AutogeneratedQuestion autogeneratedQuestion;

    @Column(name = "question_order")
    public int questionOrder;

    // standard constructors, getters, and setters
    public QuizToQuestions(Quiz quiz, OrdinaryQuestion question, int order){
        this.question = question;
        this.quiz = quiz;
        this.questionOrder = order;
    }

    public QuizToQuestions(){}

    public int getOrder(){
        return questionOrder;
    }

    @Override
    public int compareTo(QuizToQuestions o) {
        return this.questionOrder - o.questionOrder;
    }
}