package my.service.controller;


import io.swagger.v3.oas.annotations.Operation;
import org.json.JSONObject;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;

@RestController
@EnableWebMvc
public class PingController {

    @Operation(summary = "Check that server is responding",
               description = """
                       It is very convenient to use some simple GET endpoint just to check server.
                       This description was autogenerated by swagger.v3.oas annotation
                       """)
    @CrossOrigin(origins = "*", maxAge = 3600)
    @RequestMapping(path = "/ping", method = RequestMethod.GET)
    public String ping() {
        JSONObject result = new JSONObject() {{
            put("pong", "Hello, World!");
        }};
        return result.toString();
    }
}
