package my.service.quiz.repositoryInterfaces;

import my.service.quiz.entities.AutogeneratedQuestion;
import org.springframework.data.repository.CrudRepository;

public interface IAutogeneratedQuestionRepository extends CrudRepository<AutogeneratedQuestion, Integer> {
}
