package my.service.quiz.autogeneratedQuestions;

import my.service.quiz.entities.AutogeneratedQuestion;
import my.service.quiz.enums.QuestionType;

import java.util.Random;

import static my.service.quiz.Utils.generateMatrix;
import static my.service.quiz.Utils.matrixToString;

public class Question2 implements IAutogeneratedQuestion{
    @Override
    public AutogeneratedQuestion generateQuestion(String topic) {
        Random r = new Random();
        int numberOfRows = r.nextInt(5) + 1;   // from 1 to 5
        int numberOfColumns = r.nextInt(5) + 1;   // from 1 to 5
        int[][] m1 = generateMatrix(numberOfRows, numberOfColumns);


        String task = "State the dimensions (example, 5x5) for the following matrix <math-field>" + matrixToString(m1) + "</math-field>";

        String answer = numberOfRows + "x" + numberOfColumns;

        return new AutogeneratedQuestion(QuestionType.FREE_CASE_INSENSITIVE_ANSWER, task, answer, null, null, null, topic, null);
    }
}
