package my.service.quiz.autogeneratedQuestions;

import my.service.quiz.entities.AutogeneratedQuestion;
import my.service.quiz.enums.QuestionType;

import java.util.Random;

import static my.service.quiz.Utils.generateMatrix;
import static my.service.quiz.Utils.matrixToString;

/*
This code generate two 2x2 matrix and tried to check sum
solve equation - <math-field>\begin{bmatrix}4 & 5\\ 1 & -2\end{bmatrix}+\begin{bmatrix}7 & 3\\ -5 & 4\end{bmatrix}</math-field>
answer is \begin{bmatrix}11 & 8\\ -4 & 2\end{bmatrix}
 */

public class Question1 implements IAutogeneratedQuestion{
    @Override
    public AutogeneratedQuestion generateQuestion(String topic) {
        int[][] m1 = generateMatrix(2, 2);
        int[][] m2 = generateMatrix(2, 2);
        int[][] sum = sumMatrices(m1, m2);

        String task = "solve equation - <math-field>" + matrixToString(m1) + " +" + matrixToString(m2) +
                "</math-field>";

        String answer = matrixToString(sum);

        return new AutogeneratedQuestion(QuestionType.FORMULA, task, answer, null, null, null, topic, null);
    }

    private int[][] sumMatrices(int[][] m1, int[][] m2){
        // sum two 2x2 matrices:
        int[][] result = new int[2][2];
        result[0][0] = m1[0][0] + m2[0][0];
        result[0][1] = m1[0][1] + m2[0][1];
        result[1][0] = m1[1][0] + m2[1][0];
        result[1][1] = m1[1][1] + m2[1][1];
        return result;
    }
}
