package my.service.quiz.autogeneratedQuestions;

import org.springframework.stereotype.Service;

import java.util.ArrayList;

@Service
public class QuestionsGenerator {
    public ArrayList<IAutogeneratedQuestion> generator = new ArrayList<>();

    public QuestionsGenerator(){
        generator.add(new Question1());
        generator.add(new Question2());
        generator.add(new Question3());
        generator.add(new Question4());
        generator.add(new Question5());
    }
}
