package my.service.quiz.autogeneratedQuestions;

import my.service.quiz.entities.AutogeneratedQuestion;

import java.util.Random;

/*
This code generate two 2x2 matrix and tried to check sum
solve equation - <math-field>\begin{bmatrix}4 & 5\\ 1 & -2\end{bmatrix}+\begin{bmatrix}7 & 3\\ -5 & 4\end{bmatrix}</math-field>
answer is \begin{bmatrix}11 & 8\\ -4 & 2\end{bmatrix}
 */

public class Question1 implements IAutogeneratedQuestion{
    @Override
    public AutogeneratedQuestion generateQuestion() {
        int[][] m1 = generateMatrix();
        int[][] m2 = generateMatrix();
        int[][] sum = sumMatrices(m1, m2);

        String task = "solve equation - <math-field>\\begin{bmatrix}" + m1[0][0] + " & " + m1[0][1] +
                "\\\\ " + m1[1][0] + " & " + m1[1][1] + "\\end{bmatrix} " +
                "+" +
                "\\begin{bmatrix}" + m2[0][0] + " & " + m2[0][1] +
                "\\\\ " + m2[1][0] + " & " + m2[1][1] + "\\end{bmatrix}</math-field>";
        // type = 2 is case-sensitive free text answer

        String answer = "\\begin{bmatrix}" + sum[0][0] + " & " + sum[0][1] +
                "\\\\ " + sum[1][0] + " & " + sum[1][1] + "\\end{bmatrix}";

        return new AutogeneratedQuestion(2, task, answer, null, null, null, null);
    }

    private int[][] generateMatrix(){
        Random r = new Random();
        // generate 2x2 matrix
        int[][] result = new int[2][2];
        result[0][0] = r.nextInt(11) - 5;   //get int from -5 to +5
        result[0][1] = r.nextInt(11) - 5;
        result[1][0] = r.nextInt(11) - 5;
        result[1][1] = r.nextInt(11) - 5;
        return result;
    }

    private int[][] sumMatrices(int[][] m1, int[][] m2){
        // sum two 2x2 matrices:
        int[][] result = new int[2][2];
        result[0][0] = m1[0][0] + m2[0][0];
        result[0][1] = m1[0][1] + m2[0][1];
        result[1][0] = m1[1][0] + m2[1][0];
        result[1][1] = m1[1][1] + m2[1][1];
        return result;
    }
}
