package my.service.quiz.autogeneratedQuestions;

import my.service.quiz.entities.AutogeneratedQuestion;
import my.service.quiz.enums.QuestionType;

import java.util.Random;

import static my.service.quiz.Utils.generateMatrix;
import static my.service.quiz.Utils.matrixToString;

public class Question3 implements IAutogeneratedQuestion{
    @Override
    public AutogeneratedQuestion generateQuestion(String topic) {
        Random r = new Random();
        int numberOfRows = r.nextInt(5) + 1;   // from 1 to 5
        int row = r.nextInt(numberOfRows) + 1;
        int numberOfColumns = r.nextInt(5) + 1;   // from 1 to 5
        int column = r.nextInt(numberOfColumns) + 1;
        int[][] m1 = generateMatrix(numberOfRows, numberOfColumns);

        String task = "Find <math-field>S_{" + row + "," + column + "}</math-field> for the following matrix S <math-field>" + matrixToString(m1) + "</math-field>";

        String answer = m1[row - 1][column - 1] + "";

        return new AutogeneratedQuestion(QuestionType.FREE_CASE_INSENSITIVE_ANSWER, task, answer, null, null, null, topic, null);
    }
}
