package my.service.quiz.autogeneratedQuestions;

import org.springframework.stereotype.Service;

@Service
public class QuestionsGenerator {
    public IAutogeneratedQuestion[] generator;

    public QuestionsGenerator(){
        generator = new IAutogeneratedQuestion[3];
        generator[0] = new Question1();
        generator[1] = new Question2();
        generator[2] = new Question3();
    }
}
