package my.service.quiz.autogeneratedQuestions;

import org.springframework.stereotype.Service;

@Service
public class QuestionsGenerator {
    public IAutogeneratedQuestion[] generator;

    public QuestionsGenerator(){
        generator = new IAutogeneratedQuestion[1];
        generator[0] = new Question1();
    }
}
