package my.service.quiz.autogeneratedQuestions;

import my.service.quiz.entities.AutogeneratedQuestion;
import my.service.quiz.enums.QuestionType;

import java.util.Random;

public class Question4 implements IAutogeneratedQuestion{
    @Override
    public AutogeneratedQuestion generateQuestion(String topic) {
        Random r = new Random();

        int seconds = r.nextInt(10) + 1;    // random seconds number from 1 to 10
        int numberOfPis = r.nextInt(10) + 1;
        int zeroPhase = r.nextInt(10) + 1;


        String task = "Вернется ли система в исходное состояние (yes/no) после " + seconds + " секунд, " +
                "если фаза описывается следующим уровнением <math-field>\\varphi=" + numberOfPis + "\\pi t+" + zeroPhase + "</math-field>";

        String answer = (numberOfPis * seconds % 2 == 0) ? "yes" : "no";

        return new AutogeneratedQuestion(QuestionType.FREE_CASE_INSENSITIVE_ANSWER, task, answer, null, null, null, topic, null);
    }
}
