package my.service.quiz;

import my.service.quiz.autogeneratedQuestions.Question5;
import org.junit.jupiter.api.Test;
import org.springframework.util.Assert;

public class MatricesTests {

    @Test
    public void checkMatrixToStringConversionTest(){
        int[][] matrix = new int[2][2];
        matrix[0][0] = 1;
        matrix[0][1] = 2;
        matrix[1][0] = 3;
        matrix[1][1] = 4;

        String expectedResult = "\\begin{bmatrix}1 & 2\\" +
                                "\\ 3 & 4\\end{bmatrix}";

        Assert.isTrue(Utils.matrixToString(matrix).equals(expectedResult), "");
    }

    @Test
    public void multiplyMatrixTest1(){
        int[][] a = new int[2][2];
        a[0][0] = 5;   a[0][1] = 2;
        a[1][0] = 0;   a[1][1] = -2;

        int[][] b = new int[2][2];
        b[0][0] = 9;   b[0][1] = 1;
        b[1][0] = 6;   b[1][1] = -1;

        //5*9 + 2*6 = 45 + 12 = 57
        //5*1 - 2*1 = 5 - 2 = 3
        //0*9 - 2*6 = 0 - 12 = -12
        //1*0 + 2*1 = 0 + 2 = 2

        int[][] multiplicationResult = new Question5().multiplyMatrix(a, b);

        Assert.isTrue(multiplicationResult[0][0] == 57, "Expected 57 but got " + multiplicationResult[0][0]);
        Assert.isTrue(multiplicationResult[0][1] == 3, "Expected 3 but got " + multiplicationResult[0][1]);
        Assert.isTrue(multiplicationResult[1][0] == -12, "Expected -12 but got " + multiplicationResult[1][0]);
        Assert.isTrue(multiplicationResult[1][1] == 2, "Expected 2 but got " + multiplicationResult[1][1]);
    }

    @Test
    public void multiplyRowByColumnTest(){
        int[] row = new int[3];
        row[0] = 7;
        row[1] = 2;
        row[2] = -4;

        int[][] b = new int[3][2];
        b[0][0] = 7;    b[0][1] = 1;
        b[1][0] = 7;    b[1][1] = 2;
        b[2][0] = -2;   b[2][1] = 6;

        Assert.isTrue(new Question5().multiplyRowByColumn(row, b, 0) == 71, "");

    }

    @Test
    public void multiplyMatrixTest2(){
        int[][] a = new int[2][3];
        a[0][0] = 7;    a[0][1] = 2;     a[0][2] = -4;
        a[1][0] = -5;   a[1][1] = 10;    a[1][2] = 3;

        int[][] b = new int[3][2];
        b[0][0] = 7;    b[0][1] = 1;
        b[1][0] = 7;    b[1][1] = 2;
        b[2][0] = -2;   b[2][1] = 6;

        //7*7 + 2 * 7 + 2*4 = 49 + 14 + 8  = 59 + 12 = 71
        //7*1 + 2*2 - 4*6   = 7  + 4  - 24 = -13

        //-5*7 + 7*10 -3*2  = -35 + 70 - 6 = 35 - 6  = 29
        //-5*1 + 10*2 + 6*3 = -5 + 20 + 18 = 38 - 5  = 33

        // Expected result is 71 | -13
        //                    29 | 33

        int[][] multiplicationResult = new Question5().multiplyMatrix(a, b);

        Assert.isTrue(multiplicationResult[0][0] == 71, "Expected 71 but got " + multiplicationResult[0][0]);
        Assert.isTrue(multiplicationResult[0][1] == -13, "Expected -13 but got " + multiplicationResult[0][1]);
        Assert.isTrue(multiplicationResult[1][0] == 29, "Expected 29 but got " + multiplicationResult[1][0]);
        Assert.isTrue(multiplicationResult[1][1] == 33, "Expected 33 but got " + multiplicationResult[1][1]);
    }
}
